export const chaturbateCountries: Record<string, string> = {
  AT: "Østrig",
  AU: "Australien",
  BE: "Belgien",
  CA: "Canada",
  CH: "Schweiz",
  DE: "Tyskland",
  DK: "Danmark",
  FI: "Finland",
  FK: "Falklandsøerne (Malvinas)",
  FO: "Færøerne",
  FR: "Frankrig",
  GB: "Storbritannien",
  GG: "Guernsey",
  GI: "Gibraltar",
  GL: "Grønland",
  IE: "Irland",
  IS: "Island",
  JE: "Jersey",
  JP: "Japan",
  LI: "Liechtenstein",
  LU: "Luxembourg",
  NL: "Holland",
  NO: "Norge",
  NZ: "New Zealand",
  QA: "Qatar",
  SE: "Sverige",
  SG: "Singapore",
  SM: "San Marino",
  UM: "USA’s mindre ydre øer",
  US: "USA",
  VI: "Amerikanske Jomfruøer",
  AE: "De Forenede Arabiske Emirater",
  AW: "Aruba",
  BN: "Brunei Darussalam",
  BR: "Brasilien",
  BS: "Bahamas",
  CY: "Cypern",
  ES: "Spanien",
  GQ: "Ækvatorialguinea",
  GR: "Grækenland",
  HK: "Hongkong",
  IL: "Israel",
  IM: "Isle of Man",
  IT: "Italien",
  KR: "Sydkorea",
  KW: "Kuwait",
  KY: "Caymanøerne",
  MO: "Macau",
  PF: "Fransk Polynesien",
  PR: "Puerto Rico",
  PT: "Portugal",
  SI: "Slovenien",
  VG: "Britiske Jomfruøer",
  AG: "Antigua og Barbuda",
  AI: "Anguilla",
  BB: "Barbados",
  BH: "Bahrain",
  CK: "Cookøerne",
  CL: "Chile",
  CZ: "Tjekkiet",
  EE: "Estland",
  GU: "Guam",
  HR: "Kroatien",
  HU: "Ungarn",
  IN: "Indien",
  KN: "Saint Kitts og Nevis",
  LB: "Libanon",
  LT: "Litauen",
  LV: "Letland",
  MP: "Nordlige Marianerne",
  MT: "Malta",
  MX: "Mexico",
  NC: "Ny Kaledonien",
  OM: "Oman",
  PL: "Polen",
  RU: "Rusland",
  SA: "Saudi-Arabien",
  SC: "Seychellerne",
  SK: "Slovakiet",
  TR: "Tyrkiet",
  TT: "Trinidad og Tobago",
  TW: "Taiwan",
  UY: "Uruguay",
  VE: "Venezuela",
  CO: "Colombia",
  MN: "Mongoliet",
  MU: "Mauritius",
  PH: "Filippinerne",
  RO: "Rumænien",
  TH: "Thailand",
  UA: "Ukraine",
  AR: "Argentina",
  KE: "Kenya",
};